{% set name = "spiceypy" %}
{% set version = "8.0.0" %}
{% set sha256 = "f691e57290a4ff15d7e38301ebee18b09016808d45d99a6734a8e2d4a7d04d0f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - ./patches/0001-output-in-src.patch


build:
  number: 0
  skip: true  # [python_impl == 'pypy' or py<310 or win32 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]    
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]              
    - numpy                                  # [build_platform != target_platform]         
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake >=3.15
    - make  # [not win]
    - ninja  # [win]                            
  host:
    - python
    - cython >=3.1
    - numpy
    - cspice >=67,<68
    - pip
    - scikit-build-core
  run:
    - python
    - cspice >=67,<68
    - numpy

test:
  imports:
    - spiceypy
    - spiceypy.utils
    - spiceypy.cyice
  requires:
    - pytest >=7.0.0
    - pytest-benchmark
    - pandas
    - numpy >=1.23.5,<3
    - cspice >=67,<68
    - python
  commands:
    - python -m pytest --pyargs spiceypy -rpP -v --verbose --tb=long --benchmark-disable

about:
  home: https://github.com/AndrewAnnex/SpiceyPy
  license: MIT
  license_file: LICENSE
  summary: The NASA JPL NAIF SPICE toolkit wrapper written in Python

  description: |
    SpiceyPy is a python wrapper for the SPICE Toolkit. SPICE is an
    essential tool for scientists and engineers alike in the planetary
    science field for Solar System Geometry.
  doc_url: http://spiceypy.readthedocs.io/

extra:
  recipe-maintainers:
    - astrojuanlu
    - AndrewAnnex
