{% set name = "spiceypy" %}
{% set version = "2.2.0" %}
{% set sha256 = "0ffa4625e27bb94bce6243b62e708784e4ffeb938f6ae1d711a05425fb6ff7f7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

  patches:
    - 0001-Remove-CSPICE-installation-logic.patch
    - 0002-Get-rid-of-setup_requires.patch

build:
  number: 0
  noarch: python

  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - cspice ==66
    - numpy
    - six

test:
  imports:
    - spiceypy
    - spiceypy.utils

about:
  home: https://github.com/AndrewAnnex/SpiceyPy
  license: MIT
  license_file: LICENSE
  summary: 'The NASA JPL NAIF SPICE toolkit wrapper written in Python'

  description:
    - |
      SpiceyPy is a python wrapper for the SPICE Toolkit. SPICE is an
      essential tool for scientists and engineers alike in the planetary
      science field for Solar System Geometry.
  doc_url: http://spiceypy.readthedocs.io/

extra:
  recipe-maintainers:
    - juanlu001
    - AndrewAnnex
